apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: smart-alert-trigger
  namespace: smart-alert-trigger
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: eu.gcr.io/dev-avora/smart-alert-trigger:test
              imagePullPolicy: IfNotPresent
              name: smart-alert-trigger
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0-23/6
  successfulJobsHistoryLimit: 5
  suspend: false
